import type { NextPage } from "next";
import Head from "next/head";
import Banner from "../components/Banner";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const handleButtonClick = () => {};

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Coffee Finder</h1>
        <Banner
          text="View stores nearby"
          handleButtonClick={handleButtonClick}
        />
      </main>
    </div>
  );
};

export default Home;
